name: Build and push Beszel hub image

on:
  push:
    branches: [ main, ui-systems-table-spacing ]   # нужные ветки
    paths:
      - 'internal/**'
      - '.github/workflows/beszel-hub.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Сборка фронтенда -> создаём internal/site/dist
      - name: Build web UI
        run: |
          cd internal/site
          npm install
          npm run build

      # 2. Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Сборка и пуш Docker-образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: internal/dockerfile_hub
          push: true
          tags: gitclown1/beszel:latest
